# ttyS3's starship config with custom modules
# repo https://github.com/ttys3/starship-config
#
# ~/.config/starship.toml
# https://starship.rs/config/

# You can change default configuration file location with STARSHIP_CONFIG environment variable
# for example:
# export STARSHIP_CONFIG=~/.starship/config.toml

# default logs ~/.cache/starship/session_${STARSHIP_SESSION_KEY}.log
# make it custom:
# export STARSHIP_CACHE=~/.starship/cache

# Inserts a blank line between shell prompts
add_newline = true

# https://starship.rs/config/#default-prompt-format

[directory]
read_only = " "
truncation_length = 8
truncate_to_repo = false
truncation_symbol = "…/"

[status]
symbol = "🔴"
disabled = false

[git_commit]
tag_disabled = false

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[++\($count\)](green)'
renamed = "襁 "
deleted = " "
# [git_status]
# style = "bg:#E0B25D fg:#000000"
# stashed = " ${count}"
# ahead = "ﲗ ${count}"
# behind = "ﲔ ${count}"
# diverged = "李 ${ahead_count} ${behind_count}"
# conflicted = "${count}"
# deleted = " ${count}"
# renamed = "﫦${count}"
# modified = " 凜${count} "
# staged = "  ${count}"
# untracked = "  ${count}"
# format = "$all_status$ahead_behind"

[custom.os-icon]
disabled = true
command = "os-icon"
style = "bold green"
format = "[$symbol($output  )]($style)"
symbol = ""
when = "true"
shell = ["bash", "--noprofile", "--norc"]

# https://github.com/starship/starship/discussions/1252#discussioncomment-838901
[custom.git_remote_url]
description = 'Remote git repository'
disabled = true
when = 'git rev-parse --is-inside-work-tree'
command = """
GIT_REMOTE=$(command git remote get-url origin 2> /dev/null)
if [[ -z "$GIT_REMOTE" ]]; then
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
fi
GIT_REMOTE_URL=$(echo $GIT_REMOTE | sed -E 's/^https?:\\/\\/(.+@)?//; s/\\.git$//;  s/\\.git$//; s/.+@(.+):([[:digit:]]+)\\/(.+)$/\\1\\/\\3/; s/.+@(.+):(.+)$/\\1\\/\\2/; s/\\/$//')
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ -n "$GIT_REMOTE" ]]; then
    GIT_REMOTE_SYMBOL=" "
else
    GIT_REMOTE_SYMBOL=" "
fi
echo "$GIT_REMOTE_SYMBOL$GIT_REMOTE_URL"
"""
# Default format is according to the segmented-brackets preset (https://github.com/starship/starship/pull/2747)
format = '\[[$output]($style)\]'
# If you prefer the default Starship style, use the following
# format = "at [$output]($style)"
shell = ["bash", "--noprofile", "--norc"]
style = 'blue'

# symbol presets
# https://starship.rs/presets/#nerd-font-symbols
[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = "ﯣ "

[lua]
symbol = " "
